// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjdLJ7STIBXeFTQ7Zum6GQanwmrFh850Y',
    appId: '1:479949124492:web:90f0acebc1292e6da5dca9',
    messagingSenderId: '479949124492',
    projectId: 'fir-crud-basics-2281b',
    authDomain: 'fir-crud-basics-2281b.firebaseapp.com',
    storageBucket: 'fir-crud-basics-2281b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7AbtETL_-3DFYaM72LkLrArHTMK6RJrc',
    appId: '1:479949124492:android:274735f4a2cd8ceea5dca9',
    messagingSenderId: '479949124492',
    projectId: 'fir-crud-basics-2281b',
    storageBucket: 'fir-crud-basics-2281b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBl0VRgilTJ4QUQ5F_TrpSXewoSdgrark0',
    appId: '1:479949124492:ios:a52ecbd8624c65f8a5dca9',
    messagingSenderId: '479949124492',
    projectId: 'fir-crud-basics-2281b',
    storageBucket: 'fir-crud-basics-2281b.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBl0VRgilTJ4QUQ5F_TrpSXewoSdgrark0',
    appId: '1:479949124492:ios:a52ecbd8624c65f8a5dca9',
    messagingSenderId: '479949124492',
    projectId: 'fir-crud-basics-2281b',
    storageBucket: 'fir-crud-basics-2281b.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication6',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjdLJ7STIBXeFTQ7Zum6GQanwmrFh850Y',
    appId: '1:479949124492:web:6052a4c1d91b9895a5dca9',
    messagingSenderId: '479949124492',
    projectId: 'fir-crud-basics-2281b',
    authDomain: 'fir-crud-basics-2281b.firebaseapp.com',
    storageBucket: 'fir-crud-basics-2281b.firebasestorage.app',
  );
}
